### ISSUE TITLE
Textures will not load

### ISSUE THREAD

**Issue by VeilSide47** [NSACloud/RE-Mesh-Editor#2]
I can't get textures to load in Blender when importing a RE3 mesh, using default settings which have "Load Materials" and "Load MDF Material Data" enabled.

![Screenshot 2024-10-21 095608](https://github.com/user-attachments/assets/9c094f91-1720-403a-b630-385617616c94)

**Comment by NSACloud** [comment]
![image](https://github.com/user-attachments/assets/4c11bf11-eee7-496b-bc46-ee316bf06742)

It should be working, make sure you're using the correct list file when extracting the pak files.

Check the console when importing the mesh, it'll tell you what's going wrong.

Also try enabling reload cached textures in the import options.

**Comment by VeilSide47** [comment]
Thank you for your reply. The mesh I am referring to is a mod. I've tried several other RE4R mods with same results. By looking at the console it seems it cannot find referenced tex files even though they're all located in the same directory as the mesh and mdf2 file is. I guess there is no way around this problem.

**Comment by VeilSide47** [comment]
Folder structure is indeed present. I've noticed most of the tex files have been converted to dds and stored inside the project. However they still don't load properly, hence the purple color?

**Comment by NSACloud** [comment]
If you're not on blender 4.2, you can't use DDS textures. In the addon preferences, uncheck use DDS textures button and it'll use tif instead

**Comment by VeilSide47** [comment]
Unfortunately that didn't work either.

![Screenshot 2024-10-21 231915](https://github.com/user-attachments/assets/bfee7ae7-3533-4ac4-ac1f-f73bbd5426da)
![Screenshot 2024-10-21 232359](https://github.com/user-attachments/assets/3f6c8eac-98a1-4e3e-ae66-c2077da9b2fc)
![Screenshot 2024-10-21 2325223](https://github.com/user-attachments/assets/b8507fec-bb23-4a2c-9b97-8d82b7b3cd4f)
![Screenshot 2024-10-21 232741](https://github.com/user-attachments/assets/fbe1a8e9-a29c-4fe2-9a79-efe452da13ef)

**Comment by NSACloud** [comment]
I'm not sure, if they're getting converted to tif, they should be getting used.

It might be something with the version of blender you have. Maybe try installing 4.2 and seeing if it works there

**Comment by VeilSide47** [comment]
I've just tried it again using the latest Blender and not my preferred fork of Blender (Bforartists). It got better but not by much. Lots of textures are still missing and shading is all over the place. I guess I will have to accept that not all mods will work in Blender which is fine since I will only be working with meshes.

![Screenshot 2024-10-23 102600](https://github.com/user-attachments/assets/49c645cf-b19a-4086-a6bc-a46cad4cbbb0)

**Comment by NSACloud** [comment]
Textures are missing because the mod doesn't include those textures. If you extract the pak files and merge them into one folder, you can set the chunk path in the addon preferences to the chunk natives/stm/ folder and it'll use textures from there.

**Comment by VeilSide47** [comment]
Oh this is great! Didn't realize you can do that. Your addon is very powerful. I bet adding those textures from game pak files manually will solve my issue. Might as well close this thread. Thank you very much for your help.
